SELECT
  agency.agency_id,
  agency.number AS agency_number,
  agency.name AS agency_name,
  agency.preadd AS agency_preadd,
  agency.add1 AS agency_add1,
  agency.add2 AS agency_add2,
  agency.city AS agency_city,
  agency.country AS agency_country,
  agency.state AS agency_state,
  agency.zip AS agency_zip,
  agency.mailname AS agency_mailname,
  agency.mailpreadd AS agency_mailpreadd,
  agency.mailadd1 AS agency_mailadd1,
  agency.mailadd2 AS agency_mailadd2,
  agency.mailcity AS agency_mailcity,
  agency.mailstate AS agency_mailstate,
  agency.mailzip AS agency_mailzip,
  agency.mail_cntry AS agency_mail_cntry,
  agency.attention AS agency_attention,
  agency.dir_name AS agency_dir_name,
  agency.dir_notes AS agency_dir_notes,
  agency.aka AS agency_aka,
  agency.fax AS agency_fax,
  agency.email AS agency_email,
  agency.url AS agency_url,
  agency.type AS agency_type,
  agency.in_charge AS agency_in_charge,
  agency.ic_title AS agency_ic_title,
  agency.age_hours AS agency_age_hours,
  agency.notes AS agency_notes,
  agency.inc_year AS agency_inc_year,
  agency.updated AS agency_updated,
  agency.volunteer_id AS agency_volunteer_id,
  agency.org_id AS agency_org_id, -- These seem to all be AAXI (i.e. they're not unique)
  agency.entered_date AS agency_entered_date,
  agency.changed_date AS agency_changed_date,
  agency.changed_time AS agency_changed_time,
  agency.license_accreditation AS agency_license_accreditation,
  agency.irs_status AS agency_irs_status,
  agency.fein AS agency_fein,
  agency.annual_budget AS agency_annual_budget,
  agency.legal_status AS agency_legal_status,
  agency.source_of_funds AS agency_source_of_funds,
  agency.exclude_from_web AS agency_exclude_from_web,
  agency.exclude_from_dir AS agency_exclude_from_dir,
  agency.review AS agency_review,
  agency.county AS agency_county,
  agency.update_sent AS agency_update_sent,
  agency.update_returned AS agency_update_returned
FROM agency
WHERE deleted IS NULL
ORDER BY agency_id ASC
